<?php

const LIBRO = "LIBRO";
const LIB_ID = "LIB_ID";
const LIB_TITULO = "LIB_TITULO";
const LIB_AUTOR = "LIB_AUTOR";
const LIB_ISBN = "LIB_ISBN";
const LIB_EDITORIAL = "LIB_EDITORIAL";
const LIB_MODIFICACION = "LIB_MODIFICACION";
const LIB_ELIMINADO = "LIB_ELIMINADO";